### ISSUE TITLE
error: ‘rb_cFixnum’ undeclared

### ISSUE THREAD

**Issue by igouy** [srawlins/gmp#13]
Linux x64 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]

$ cd /usr/local/src/ruby-gmp-master/ext

$ /usr/local/src/ruby/bin/ruby extconf.rb
checking for gmp.h... yes
checking for __gmpz_init() in -lgmp... yes
checking for mpfr.h... yes
checking for mpf2mpfr.h... yes
checking for mpfr_init() in -lmpfr... yes
checking for SIZEOF_INTPTR_T... yes
creating Makefile

$ make
compiling gmp.c
gmp.c: In function ‘Init_gmp’:
gmp.c:165:19: error: ‘rb_cFixnum’ undeclared (first use in this function)
   rb_define_alias(rb_cFixnum, old_fname, ruby_fname); \
                   ^
gmp.c:222:3: note: in expansion of macro ‘REGISTER_TAKEOVER’
   REGISTER_TAKEOVER(and, "&", "old_and")
   ^
gmp.c:165:19: note: each undeclared identifier is reported only once for each function it appears in
   rb_define_alias(rb_cFixnum, old_fname, ruby_fname); \
                   ^
gmp.c:222:3: note: in expansion of macro ‘REGISTER_TAKEOVER’
   REGISTER_TAKEOVER(and, "&", "old_and")
   ^
gmp.c:167:19: error: ‘rb_cBignum’ undeclared (first use in this function)
   rb_define_alias(rb_cBignum, old_fname, ruby_fname); \
                   ^
gmp.c:222:3: note: in expansion of macro ‘REGISTER_TAKEOVER’
   REGISTER_TAKEOVER(and, "&", "old_and")
   ^
gmp.c: At top level:
cc1: warning: unrecognized command line option ‘-Wno-self-assign’
cc1: warning: unrecognized command line option ‘-Wno-constant-logical-operand’
cc1: warning: unrecognized command line option ‘-Wno-parentheses-equality’
cc1: warning: unrecognized command line option ‘-Wno-tautological-compare’
Makefile:241: recipe for target 'gmp.o' failed
make: *** [gmp.o] Error 1

**Comment by kylekyle** [comment]
Ruby 2.4 only supports [Fixnum/Bignum unification](https://bugs.ruby-lang.org/issues/12005). Switching from `rb_cFixnum` to `rb_cInteger` should fix this (and is backward compatible back to Ruby 2.0.0).
