### ISSUE TITLE
gmp.c:165:19: error: ‘rb_cFixnum’ undeclared

### ISSUE THREAD

**Issue by igouy** [srawlins/gmp#16]
Ubuntu 17.10
gcc (Ubuntu 7.2.0-8ubuntu3) 7.2.0

$ /opt/src/ruby-2.5.0/bin/gem install --local ./gmp-0.7.19.gem
Building native extensions. This could take a while...
ERROR:  Error installing ./gmp-0.7.19.gem:
	ERROR: Failed to build gem native extension.

    current directory: /opt/src/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/gmp-0.7.19/ext
/opt/src/ruby-2.5.0/bin/ruby -r ./siteconf20180102-2402-qrgh2q.rb extconf.rb
checking for gmp.h... yes
checking for __gmpz_init() in -lgmp... yes
checking for mpfr.h... no
checking for SIZEOF_INTPTR_T... yes
creating Makefile

current directory: /opt/src/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/gmp-0.7.19/ext
make "DESTDIR=" clean

current directory: /opt/src/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/gmp-0.7.19/ext
make "DESTDIR="
compiling gmp.c
gmp.c: In function ‘Init_gmp’:
gmp.c:165:19: error: ‘rb_cFixnum’ undeclared (first use in this function); did you mean ‘rb_isalnum’?
   rb_define_alias(rb_cFixnum, old_fname, ruby_fname); \
                   ^
gmp.c:222:3: note: in expansion of macro ‘REGISTER_TAKEOVER’
   REGISTER_TAKEOVER(and, "&", "old_and")
   ^~~~~~~~~~~~~~~~~
gmp.c:165:19: note: each undeclared identifier is reported only once for each function it appears in
   rb_define_alias(rb_cFixnum, old_fname, ruby_fname); \
                   ^
gmp.c:222:3: note: in expansion of macro ‘REGISTER_TAKEOVER’
   REGISTER_TAKEOVER(and, "&", "old_and")
   ^~~~~~~~~~~~~~~~~
gmp.c:167:19: error: ‘rb_cBignum’ undeclared (first use in this function); did you mean ‘rb_cFixnum’?
   rb_define_alias(rb_cBignum, old_fname, ruby_fname); \
                   ^
gmp.c:222:3: note: in expansion of macro ‘REGISTER_TAKEOVER’
   REGISTER_TAKEOVER(and, "&", "old_and")
   ^~~~~~~~~~~~~~~~~
gmp.c: At top level:
cc1: warning: unrecognized command line option ‘-Wno-self-assign’
cc1: warning: unrecognized command line option ‘-Wno-constant-logical-operand’
cc1: warning: unrecognized command line option ‘-Wno-parentheses-equality’
Makefile:241: recipe for target 'gmp.o' failed
make: *** [gmp.o] Error 1

make failed, exit code 2

Gem files will remain installed in /opt/src/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/gmp-0.7.19 for inspection.
Results logged to /opt/src/ruby-2.5.0/lib/ruby/gems/2.5.0/extensions/x86_64-linux/2.5.0-static/gmp-0.7.19/gem_make.out

**Comment by timocp** [comment]
You're using gmp 0.7.19 which isn't compatible with ruby 2.4 or newer.  Try using version 0.7.43 of the gmp gem.

**Comment by igouy** [comment]
Thanks. Don't know how I came to download an old version.
